version: '3.3'
services:  
    patee-cinema:
        ports:
            - '80:80'
        container_name: patee
        image: 'pateecinema/patee-cinema:latest'
        environment:
            hostname: ${hostname}
            username: ${username}
            password: ${password}
            database: ${database}
            StripePubKey: ${StripePubKey}
            StripeKey: ${StripeKey}
            AppUrl: ${AppUrl}